# -*- coding: utf-8 -*-
"""Cópia de Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jom7EgfVkFgG3j2_iXjXbUv7AL6IY8At
"""

!pip install SpeechRecognition pydub gTTS

import speech_recognition as sr
from pydub import AudioSegment
from gtts import gTTS
from IPython.display import Audio

def generate_audio(text, filename="audio.mp3"):
    """Gera um arquivo de áudio a partir do texto."""
    tts = gTTS(text=text, lang='pt-br')
    tts.save(filename)

def extrair_texto_do_audio(audio_file):
  """Extrai o texto falado de um arquivo de áudio.

  Args:
    audio_file: O nome do arquivo de áudio.

  Returns:
    O texto extraído do áudio.
  """
  r = sr.Recognizer()
  with sr.AudioFile(audio_file) as source:
    audio_data = r.record(source)
    text = r.recognize_google(audio_data, language="pt-BR")
  return text

# Gerar áudio sobre o sistema solar
texto_sistema_solar = """
O sistema solar é um sistema planetário composto pelo Sol e pelos corpos celestes que orbitam ao seu redor, incluindo planetas, luas, asteroides e cometas.
O Sol é uma estrela que contém a maior parte da massa do sistema solar e sua gravidade mantém os outros corpos em órbita.
Os oito planetas do sistema solar, em ordem de distância do Sol, são: Mercúrio, Vênus, Terra, Marte, Júpiter, Saturno, Urano e Netuno.
A Terra é o único planeta conhecido por abrigar vida.
"""
generate_audio(texto_sistema_solar, "audio_sistema_solar.mp3")

# Converter o áudio para WAV
audio = AudioSegment.from_file("audio_sistema_solar.mp3", format="mp3")
audio.export("audio_sistema_solar.wav", format="wav")

# Reproduzir o áudio
print("Reproduzindo áudio sobre o sistema solar:")
display(Audio("audio_sistema_solar.mp3", autoplay=True))

# Extrair o texto do áudio gerado (usando o nome do arquivo WAV)
texto_extraido = extrair_texto_do_audio("audio_sistema_solar.wav")

# Exibir o texto extraído
print("\nTexto extraído do áudio:")
print(texto_extraido)