# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NfXAzTb8cUzcIxj3KlZK5PUXoFM2Ce1Y
"""

!pip install gTTS==2.3.1
from gtts import gTTS
from IPython.display import Audio

# Define o texto que será convertido em fala
texto = "A inteligência Artificial, está em todos os lugares do planeta!"

# Cria um objeto gTTS com o texto e o idioma desejado
tts = gTTS(text=texto, lang='pt-br')

# Salva o áudio gerado em um arquivo temporário
tts.save("saida_em_voz.mp3")

# Reproduz o áudio usando IPython.display.Audio
display(Audio("saida_em_voz.mp3", autoplay=True))

!pip install gTTS==2.3.1
from gtts import gTTS
from IPython.display import Audio

# Define o texto que será convertido em fala
texto = "Este é o resultado da saída em voz falada."

# Cria um objeto gTTS com o texto e o idioma desejado
tts = gTTS(text=texto, lang='pt-br')

# Salva o áudio gerado em um arquivo temporário
tts.save("saida_em_voz.mp3")

# Reproduz o áudio usando IPython.display.Audio
display(Audio("saida_em_voz.mp3", autoplay=True))

!pip install gTTS==2.3.1

from gtts import gTTS
from IPython.display import Audio

tts = gTTS(text='A inteligência Artificial, está em todos os lugares do planeta! ', lang='pt-br')
audio_data = tts.save("audio_data.wav") # Salva os dados em audio_data